version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  frontend:
    build: ./frontend
    labels:
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - web

  backend:
    build: ./backend
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`, `/docs`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    networks:
      - web

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: app
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - web

volumes:
  pgdata:

networks:
  web:


  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '8090:80'
      - '81:81'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - web
